using System.Collections.Generic;

namespace Rewards
{
    public class WordList
    {
        public static List<string> SearchDictionary = new List<string>()
        {
            "pineapple",
            "orange",
            "caviar",
            "milk",
            "butter",
            "cheese",
            "flour",
            "water",
            "c#",
            "perl",
            "php",
            "python",
            "Utah Jazz",
                "Bojan Bogdanovic",
                "Tony Bradley",
                "Jarrell Brantley",
                "Jordan Clarkson",
                "Mike Conley",
                "Ed Davis",
                "Rudy Gobert",
                "Joe Ingles",
                "Donovan Mitchell",
                "Juwan Morgan",
                "Emmanuel Mudiay",
                "Georges Niang",
                "Royce O'Neale",
                "Miye Oni",
                "Rayjon Tucker",
                "Nigel Williams-Goss",
                "Justin Wright-Foreman",
            "Denver Nuggets",
                "Will Barton",
                "Keita Bates-Diop",
                "Bol Bol",
                "Vlatko Cancar",
                "Torrey Craig",
                "Troy Daniels",
                "PJ Dozier",
                "Jerami Grant",
                "Gary Harris",
                "Nikola Jokic",
                "Paul Millsap",
                "Monte Morris",
                "Jamal Murray",
                "Mason Plumlee",
                "Michael Porter Jr.",
                "Noah Vonleh",
            "Washington Wizards",
                "Bradley Beal",
                "Davis Bertans",
                "Isaac Bonga",
                "Troy Brown Jr.",
                "Thomas Bryant",
                "Rui Hachimura",
                "Ian Mahinmi",
                "Garrison Mathews",
                "Shabazz Napier",
                "Anzejs Pasecniks",
                "Gary Payton II",
                "Jerome Robinson",
                "Admiral Schofield",
                "Ish Smith",
                "Moritz Wagner",
                "John Wall",
                "Johnathan Williams",
            "MLS",
                "Andrea Pirlo",
                "Tim Howard",
                "Reto Ziegler",
                "Alexander Büttner",
                "Ilsinho",
                "Bacary Sagna",
                "Romain Alessandrini",
                "Gregory van der Wiel",
                "Sebastián Blanco",
                "José Ángel",
                "Michael Bradley",
                "Giovani dos Santos",
                "Guram Kashia",
                "Adolfo Bautista",
                "Maynor Figueroa",
                "Jonathan dos Santos",
                "Emanuel Pogatetz",
                "Chris Wondolowski",
                "Jermaine Jones",
                "Benoit Cheyrou",
                "Jerry Bengtson",
                "Peguy Luyindula",
                "Blas Pérez",
                "Andreu Fontàs",
                "Laurent Ciman",
                "Fabián Castillo",
                "Kellyn Acosta",
                "Rod Fanni",
                "DaMarcus Beasley",
                "Alejandro Bedoya",
                "Matteo Ferrari",
                "Andoni Iraola",
                "Geoffrey Castillion",
                "Ibrahim Sekagya",
                "Valeri Kazaishvili",
                "Adam Henley",
                "Kevin Doyle",
                "Sacha Kljestan",
                "Răzvan Cociș",
                "Jozy Altidore",
                "Shaun Maloney",
                "Marco Donadel",
                "Luke Moore",
                "Richard Sánchez",
                "Hendry Thomas",
                "Peter Luccin",
                "Rodney Wallace",
                "Carlos Gruezo",
                "Waylon Francis",
                "Érick Torres",
                "Michael Parkhurst",
                "Benny Feilhaber",
                "Mike Magee",
                "Justin Mapp",
                "Graham Zusi",
                "Luis Gil",
                "Tim Payne",
                "Federico Higuaín",
                "Chad Marshall",
                "Kenny Cooper",
                "Gastón Fernández",
                "Diego Valeri",
                "Brad Davis",
                "Eric Brunner",
                "Edson Buddle",
                "Juan Agudelo",
                "Marvin Chávez",
                "Tony Beltran",
                "Sean Johnson",
                "Matt Besler",
                "Will Bruin",
                "Jack McInerney",
                "Kyle Beckerman",
                "Shkëlzen Gashi",
                "Tony Lochhead",
                "Erick",
                "Terrence Boyd",
                "Clarence Goodson",
                "Álvaro Fernández",
                "Cristian Lobato",
                "Efraín Juárez",
                "Bradley Wright-Phillips",
                "Diego Polenta",
                "Kennedy Igboananike",
                "David Accam",
                "Anton Tinnerholm",
                "Jørgen Skjelvik",
                "Gastón Sauro",
                "Gláuber",
                "Daniel Royer",
                "Ruben Bover",
                "Joe Bendik",
                "Wilman Conde",
                "Víctor Bernárdez",
                "Ricardo Clark",
                "Roy Miller",
                "Oscar Boniek García",
                "Nigel Reo-Coker",
                "Digão",
                "Steven Caldwell",
                "Mauro Rosales",
                "Mauro Díaz",
                "Ignacio Piatti",
                "Haris Medunjanin",
                "Maurice Edu",
                "Kelvin Leerdam",
                "Johan Kappelhof",
                "Jonathan Mensah",
                "Jean-Baptiste Pierazzi",
                "Michael Mancienne",
                "Marcel De Jong",
                "Marco Ureña",
                "Gustav Svensson",
                "Kei Kamara",
                "Nedum Onuoha",
                "Liam Ridgewell",
                "David Texeira",
                "Krisztián Németh",
                "Felipe Gutiérrez",
                "Zoltán Stieber",
                "Adrián López",
                "José Mari",
                "Alejandro Pozuelo",
            "NFL Players",
                "Quarterbacks",
                "Josh Allen",
                "Tom Brady",
                "Drew Brees",
                "Teddy Bridgewater",
                "Joe Burrow",
                "Derek Carr",
                "Kirk Cousins",
                "Sam Darnold",
                "Ryan Fitzpatrick",
                "Jimmy Garoppolo",
                "Jared Goff",
                "Dwayne Haskins",
                "Taysom Hill",
                "Lamar Jackson",
                "Daniel Jones",
                "Drew Lock",
                "Patrick Mahomes",
                "Baker Mayfield",
                "Gardner Minshew",
                "Kyler Murray",
                "Dak Prescott",
                "Philip Rivers",
                "Aaron Rodgers",
                "Ben Roethlisberger",
                "Matt Ryan",
                "Matthew Stafford",
                "Jarrett Stidham",
                "Ryan Tannehill",
                "Tyrod Taylor",
                "Mitchell Trubisky",
                "Deshaun Watson",
                "Carson Wentz",
                "Russell Wilson",
                "Running Backs",
                "Cam Akers",
                "Saquon Barkley",
                "Le'Veon Bell",
                "Giovani Bernard",
                "Reggie Bonnafon",
                "Matt Breida",
                "Chris Carson",
                "Nick Chubb",
                "Tarik Cohen",
                "Tevin Coleman",
                "James Conner",
                "Dalvin Cook",
                "JK Dobbins",
                "Kenyan Drake",
                "Chase Edmonds",
                "Clyde Edwards-Helaire",
                "Austin Ekeler",
                "Ezekiel Elliott",
                "Darrynton Evans",
                "Leonard Fournette",
                "Melvin Gordon",
                "Frank Gore",
                "Derrius Guice",
                "Todd Gurley",
                "Darrell Henderson",
                "Derrick Henry",
                "Jordan Howard",
                "Kareem Hunt",
                "Mark Ingram",
                "Justin Jackson",
                "Josh Jacobs",
                "Kerryon Johnson",
                "David Johnson",
                "Duke Johnson",
                "Aaron Jones",
                "Ronald Jones",
                "Alvin Kamara",
                "Dion Lewis",
                "Phillip Lindsay",
                "Marlon Mack",
                "Alexander Mattison",
                "Christian McCaffrey",
                "Sony Michel",
                "Joe Mixon",
                "David Montgomery",
                "Zack Moss",
                "Raheem Mostert",
                "Latavius Murray",
                "Rashaad Penny",
                "Adrian Peterson",
                "Tony Pollard",
                "Jalen Richard",
                "Jaylen Samuels",
                "Miles Sanders",
                "Boston Scott",
                "Devin Singletary",
                "Ito Smith",
                "D'Andre Swift",
                "Jonathan Taylor",
                "Chris Thompson",
                "Ke'Shawn Vaughn",
                "James White",
                "Jamaal Williams",
                "Damien Williams",
                "Wide Receivers",
                "Davante Adams",
                "Nelson Agholor",
                "Brandon Aiyuk",
                "Keenan Allen",
                "Geronimo Allison",
                "Danny Amendola",
                "Robby Anderson",
                "JJ Arcega-Whiteside",
                "Cameron Batson",
                "Cole Beasley",
                "Odell Beckham Jr.",
                "Chad Beebe",
                "Braxton Berrios",
                "Christian Blake",
                "Kendrick Bourne",
                "Tyler Boyd",
                "Miles Boykin",
                "Marquise Brown",
                "AJ Brown",
                "John Brown",
                "Ventell Bryant",
                "Hakeem Butler",
                "Damiere Byrd",
                "Deon Cain",
                "Parris Campbell",
                "DeAndre Carter",
                "Quintez Cephus",
                "D.J. Chark",
                "Chase Claypool",
                "Randall Cobb",
                "Keelan Cole",
                "Corey Coleman",
                "Chris Conley",
                "Brandin Cooks",
                "Pharoh Cooper",
                "Amari Cooper",
                "Cody Core",
                "Keke Coutee",
                "Jamison Crowder",
                "Corey Davis",
                "Felton Davis III",
                "Stefon Diggs",
                "Josh Doctson",
                "Phillip Dorsett",
                "Greg Dortch",
                "Devin Duvernay",
                "Julian Edelman",
                "Bryan Edwards",
                "Alex Erickson",
                "Mike Evans",
                "Larry Fitzgerald",
                "Isaiah Ford",
                "John Franklin",
                "Will Fuller",
                "Devin Funchess",
                "Russell Gage",
                "Michael Gallup",
                "Antonio Gandy-Golden",
                "Ted Ginn Jr.",
                "Chris Godwin",
                "Kenny Golladay",
                "Marquise Goodwin",
                "Jakeem Grant",
                "Devin Gray",
                "A.J. Green",
                "Marvin Hall",
                "DaeSean Hamilton",
                "KJ Hamler",
                "Mecole Hardman",
                "Kelvin Harmon",
                "Deonte Harris",
                "N'Keal Harry",
                "Rashard Higgins",
                "Tee Higgins",
                "Tyreek Hill",
                "T.Y. Hilton",
                "KhaDarel Hodge",
                "Krishawn Hogan",
                "Cody Hollister",
                "DeAndre Hopkins",
                "Adam Humphries",
                "Jalen Hurd",
                "Allen Hurns",
                "Andy Isabella",
                "DeSean Jackson",
                "Justin Jefferson",
                "Van Jefferson",
                "Alshon Jeffery",
                "Darius Jennings",
                "Jerry Jeudy",
                "Tyler Johnson",
                "KeeSean Johnson",
                "Marcus Johnson",
                "Diontae Johnson",
                "Olabisi Johnson",
                "Collin Johnson",
                "Marvin Jones",
                "Julio Jones",
                "Zay Jones",
                "Christian Kirk",
                "Keith Kirkwood",
                "Jake Kumerow",
                "Cooper Kupp",
                "CeeDee Lamb",
                "Jarvis Landry",
                "Cody Latimer",
                "Allen Lazard",
                "Marqise Lee",
                "Tyler Lockett",
                "Isaiah McKenzie",
                "Terry McLaurin",
                "DK Metcalf",
                "Jakobi Meyers",
                "Anthony Miller",
                "Scott Miller",
                "Denzel Mims",
                "David Moore",
                "Chris Moore",
                "D.J. Moore",
                "Jason Moore",
                "KJ Osborn",
                "DeVante Parker",
                "Zach Pascal",
                "Dezmon Patmon",
                "Tim Patrick",
                "Cordarrelle Patterson",
                "Andre Patton",
                "Donovan Peoples-Jones",
                "Breshad Perriman",
                "Dante Pettis",
                "Michael Pittman Jr",
                "Byron Pringle",
                "Trey Quinn",
                "Damion Ratley",
                "Kalif Raymond",
                "Jalen Reagor",
                "Joe Reed",
                "Hunter Renfrow",
                "Josh Reynolds",
                "Calvin Ridley",
                "Riley Ridley",
                "Andre Roberts",
                "Seth Roberts",
                "Allen Robinson",
                "Demarcus Robinson",
                "John Ross",
                "Henry Ruggs III",
                "Curtis Samuel",
                "Deebo Samuel",
                "Emmanuel Sanders",
                "Mohamed Sanu",
                "Da'Mari Scott",
                "Tajae Sharpe",
                "Laviska Shenault Jr",
                "Sterling Shepard",
                "Steven Sims",
                "Darius Slayton",
                "Tre'Quan Smith",
                "Devin Smith",
                "Vyncint Smith",
                "JuJu Smith-Schuster",
                "Willie Snead",
                "Diontae Spencer",
                "Equanimeous St. Brown",
                "Kenny Stills",
                "Courtland Sutton",
                "Freddie Swain",
                "Ryan Switzer",
                "Auden Tate",
                "Golden Tate",
                "Trent Taylor",
                "Adam Thielen",
                "Michael Thomas",
                "De'Anthony Thomas",
                "John Ursua",
                "Marquez Valdes-Scantling",
                "Greg Ward",
                "James Washington",
                "Sammy Watkins",
                "Justin Watson",
                "Nsimba Webster",
                "Dede Westbrook",
                "Duke Williams",
                "Tyrell Williams",
                "Preston Williams",
                "Mike Williams",
                "Cedrick Wilson",
                "Albert Wilson",
                "Javon Wims",
                "Robert Woods",
                "Olamide Zaccheaus",
            "NHL",
                "David Pastrnak",
                "Leon Draisaitl",
                "Connor McDavid",
                "Nikita Kucherov",
                "Artemi Panarin",
                "Nathan MacKinnon",
                "Auston Matthews",
                "Patrick Kane",
                "Alex Ovechkin",
                "Brad Marchand",
                "Mika Zibanejad",
                "Tuukka Rask",
                "Andrei Vasilevskiy",
                "Sidney Crosby",
                "John Carlson",
                "Patrice Bergeron",
                "Mitchell Marner",
                "Jonathan Huberdeau",
                "Max Pacioretty",
                "Elias Pettersson",
                "Steven Stamkos",
                "Dougie Hamilton",
                "Roman Josi",
                "Evgeni Malkin",
                "Jack Eichel",
                "Victor Hedman",
                "J.T. Miller",
                "Brayden Point",
                "Ben Bishop",
                "Jordan Binnington",
                "Mark Stone",
                "Jake Guentzel",
                "Cale Makar",
                "Mikko Rantanen",
                "Patrik Laine",
                "Matthew Tkachuk",
                "Blake Wheeler",
                "Mark Scheifele",
                "Claude Giroux",
                "Kyle Connor",
                "Alex Pietrangelo",
                "Quinn Hughes",
                "Sebastian Aho",
                "Andrei Svechnikov",
                "Aleksander Barkov",
                "Ryan Nugent-Hopkins",
                "Marc-Andre Fleury",
                "Vladimir Tarasenko",
                "Connor Hellebuyck",
                "John Tavares",
                "Carter Hart",
                "Torey Krug",
                "Kris Letang",
                "Tyler Seguin",
                "Johnny Gaudreau",
                "Teuvo Teravainen",
                "Gabriel Landeskog",
                "Sean Couturier",
                "Anze Kopitar",
                "Travis Konecny",
                "Frederik Andersen",
                "Chris Kreider",
                "William Nylander",
                "Shea Theodore",
                "David Perron",
                "Tom Wilson",
                "Igor Shesterkin",
                "Brady Tkachuk",
                "Jacob Markstrom",
                "Evgeny Kuznetsov",
                "Brayden Schenn",
                "Jonathan Marchessault",
                "Bryan Rust",
                "Jamie Benn",
                "Ryan O'Reilly",
                "Nicklas Backstrom",
                "Kevin Fiala",
                "Brock Boeser",
                "Pavel Francouz",
                "Tony DeAngelo",
                "Morgan Rielly",
                "Robin Lehner",
                "Evander Kane",
                "Neal Pionk",
                "Taylor Hall",
                "Mike Hoffman",
                "Elias Lindholm",
                "Ryan Ellis",
                "Darcy Kuemper",
                "Jaroslav Halak",
                "T.J. Oshie",
                "Nikolaj Ehlers",
                "Reilly Smith",
                "Jakub Vrana",
                "Mathew Barzal",
                "Juuse Saros",
                "Ivan Provorov",
                "Brendan Gallagher",
                "Filip Forsberg",
                "Kailer Yamamoto",
                "Tomas Tatar",
                "Brent Burns",
                "Erik Karlsson",
                "Braden Holtby",
                "Charlie McAvoy",
                "Mark Giordano",
                "Logan Couture",
                "Bo Horvat",
                "Matt Murray",
                "Petr Mrazek",
                "Tyson Barrie",
                "Keith Yandle",
                "Tyler Toffoli",
                "Jakub Voracek",
                "Elvis Merzlikins",
                "John Klingberg",
                "Rasmus Dahlin",
                "Mikhail Sergachev",
                "Jeff Petry",
                "Jaden Schwartz",
                "Jason Zucker",
                "Timo Meier",
                "Anthony Mantha",
                "Alexander Radulov",
                "Dominik Kubalik",
                "Victor Olofsson",
                "Philipp Grubauer",
                "Sergei Bobrovsky",
                "Shea Weber",
                "Tristan Jarry",
                "Semyon Varlamov",
                "Carey Price",
                "Seth Jones",
                "Pavel Buchnevich",
                "Ryan Strome",
                "William Karlsson",
                "Zach Hyman",
                "Patric Hornqvist",
                "Ondrej Palat",
                "Dylan Larkin",
                "Evgenii Dadonov",
                "Oscar Klefbom",
                "Joonas Korpisalo",
                "Jonathan Toews",
                "Pierre-Luc Dubois",
                "Thomas Chabot",
                "Sean Monahan",
                "Tomas Hertl",
                "Mackenzie Blackwood",
                "Matt Niskanen",
                "Alex Stalock",
                "Antti Raanta",
                "Alexander Edler",
                "Ryan Graves",
                "Clayton Keller",
                "Oliver Bjorkstrand",
                "Mikko Koskinen",
                "Anton Khudobin",
                "Sam Reinhart",
                "Max Domi",
                "Cam Atkinson",
                "Kyle Palmieri",
                "Alex DeBrincat",
                "Nick Foligno",
                "Ilya Kovalchuk",
                "Andre Burakovsky",
                "Adam Fox",
                "Ryan Suter",
                "Aaron Ekblad",
                "Alex Iafallo",
                "Cam Talbot",
                "Anthony Cirelli",
                "Anders Lee",
                "Nikita Gusev",
                "Zach Parise",
                "Corey Crawford",
                "Ilya Samsonov",
                "Anthony Duclair",
                "Nazem Kadri",
                "Jaccob Slavin",
                "Colton Parayko",
                "Miro Heiskanen",
                "Oliver Ekman-Larsson",
                "Vincent Trocheck",
                "Paul Stastny",
                "Brock Nelson",
                "Duncan Keith",
                "Mikael Backlund",
                "Kevin Hayes",
                "Alex Killorn",
                "Vladislav Namestnikov",
                "Zack Kassian",
                "Jordan Eberle",
                "Eric Staal",
                "Yanni Gourde",
                "Dylan Strome",
                "Chris Driedger",
                "Thatcher Demko",
                "Jake Muzzin",
                "Denis Gurianov",
                "Alec Martinez",
                "Jared Spurgeon",
                "Andreas Athanasiou",
                "Drew Doughty",
                "Jakob Chychrun",
                "Dustin Brown",
                "Andrew Mangiapane",
                "Adam Henrique",
                "Emil Bemstrom",
                "Vince Dunn",
                "Calvin Petersen",
                "Rickard Rakell",
                "Rasmus Ristolainen",
                "Darnell Nurse",
                "Conor Garland",
                "Gustav Nyquist",
                "Jacob Trouba",
                "Jean-Gabriel Pageau",
                "Nick Suzuki",
                "Robert Thomas",
                "Zach Sanford",
                "John Gibson",
                "David Krejci",
                "Ryan Pulock",
                "Mattias Ekholm",
                "Joel Armia",
                "Alexandar Georgiev",
                "Jonathan Drouin",
                "James Reimer",
                "Phillip Danault",
                "Sami Vatanen",
                "Ryan Getzlaf",
                "Kaapo Kakko",
                "Erik Gustafsson",
                "Alex Goligoski",
                "Josh Morrissey",
                "Mike Smith",
                "David Rittich",
                "Filip Zadina",
                "Tyler Bertuzzi",
                "Jonathan Quick",
                "Roope Hintz",
                "Linus Ullmark",
                "Ondrej Kase",
                "Jake Allen",
                "Kevin Shattenkirk",
                "John Marino",
                "Nico Hischier",
                "Kirby Dach",

            // basketball
            "Atlanta Hawks",
            "Boston Celtics",
            "Brooklyn Nets",
            "Charlotte Hornets",
            "Chicago Bulls",
            "Cleveland Cavaliers",
            "Dallas Mavericks",
            "Denver Nuggets",
            "Detroit Pistons",
            "Golden State Warriors",
            "Houston Rockets",
            "Indiana Pacers",
            "Los Angeles Clippers",
            "Los Angeles Lakers",
            "Memphis Grizzlies",
            "Miami Heat",
            "Milwaukee Bucks",
            "Minnesota Timberwolves",
            "New Orleans Pelicans",
            "New York Knicks",
            "Oklahoma City Thunder",
            "Orlando Magic",
            "Philadelphia 76ers",
            "Phoenix Suns",
            "Portland Trail Blazers",
            "Sacramento Kings",
            "San Antonio Spurs",
            "Toronto Raptors",
            "Utah Jazz",
            "Washington Wizards",

            // Baseball
            "Baltimore Orioles",
            "Boston Red Sox",
            "Chicago White Sox",
            "Cleveland Indians",
            "Detroit Tigers",
            "Houston Astros",
            "Kansas City Royals",
            "Los Angeles Angels",
            "Minnesota Twins",
            "New York Yankees",
            "Oakland Athletics",
            "Seattle Mariners",
            "Tampa Bay Rays",
            "Texas Rangers",
            "Toronto Blue Jays",

            "Milwaukee Brewers",
            "Chicago Cubs",
            "Cincinnati Reds",
            "Pittsburgh Pirates",
            "St. Louis Cardinals",
            "Atlanta Braves",
            "Washington Nationals",
            "New York Mets",
            "Philadelphia Phillies",
            "Miami Marlins",
            "Los Angeles Dodgers",
            "San Diego Padres",
            "San Francisco Giants",
            "Colorado Rockies",
            "Arizona Diamondbacks",

            // Olympic Host cities
            "Athens, Greece",
            "Paris, France",
            "St. Louis, United States",
            "London, United Kingdom",
            "Stockholm, Sweden",
            "Antwerp, Belgium",
            "Chamonix, France",
            "Paris, France",
            "St. Moritz,  Switzerland",
            "Amsterdam, Netherlands",
            "Lake Placid, United States",
            "Los Angeles, United States",
            "Garmisch-Partenkirchen, Nazi Germany",
            "Berlin, Nazi Germany",
            "St. Moritz,  Switzerland",
            "London, United Kingdom",
            "Oslo, Norway",
            "Helsinki, Finland",
            "Cortina d’Ampezzo, Italy",
            "Melbourne, Australia",
            "Stockholm, Sweden",
            "Squaw Valley, United States",
            "Rome, Italy",
            "Innsbruck, Austria",
            "Tokyo, Japan",
            "Grenoble, France",
            "Mexico City, Mexico",
            "Sapporo, Japan",
            "Munich, West Germany",
            "Innsbruck, Austria",
            "Montreal, Canada",
            "Lake Placid, United States",
            "Moscow, Soviet Union",
            "Sarajevo, Yugoslavia",
            "Los Angeles, United States",
            "Calgary, Canada",
            "Seoul, South Korea",
            "Albertville, France",
            "Barcelona, Spain",
            "Lillehammer, Norway",
            "Atlanta, United States",
            "Nagano, Japan",
            "Sydney, Australia",
            "Salt Lake City, United States",
            "Athens, Greece",
            "Torino, Italy",
            "Beijing, China",
            "Vancouver, Canada",
            "London, United Kingdom",
            "Sochi, Russia",
            "Rio de Janeiro, Brazil",
            "Pyeongchang, South Korea",
            "Tokyo, Japan",
            "Beijing, China",
            "Paris, France",
            "Los Angeles, United States",

            // Presidents
            "George Washington",
            "John Adams",
            "Thomas Jefferson",
            "James Madison",
            "James Monroe",
            "John Quincy Adams",
            "Andrew Jackson",
            "Martin Van Buren",
            "William H. Harrison",
            "John Tyler",
            "James K. Polk",
            "Zachary Taylor",
            "Millard Fillmore",
            "Franklin Pierce",
            "James Buchanan",
            "Abraham Lincoln",
            "Andrew Johnson",
            "Ulysses S. Grant",
            "Rutherford B. Hayes",
            "James A. Garfield",
            "Chester A. Arthur",
            "Grover Cleveland",
            "Benjamin Harrison",
            "Grover Cleveland",
            "William McKinley",
            "Theodore Roosevelt",
            "William H. Taft",
            "Woodrow Wilson",
            "Warren G. Harding",
            "Calvin Coolidge",
            "Herbert Hoover",
            "Franklin D. Roosevelt",
            "Harry S. Truman",
            "Dwight D. Eisenhower",
            "John F. Kennedy",
            "Lyndon B. Johnson",
            "Richard M. Nixon",
            "Gerald R. Ford",
            "Jimmy Carter",
            "Ronald Reagan",
            "George H. W. Bush",
            "Bill Clinton",
            "George W. Bush",
            "Barack Hussein Obama",
            "Donald J. Trump",

        };
    }
}
